### ISSUE TITLE
🐛  - slash(/) does nothing in ubuntu

### ISSUE THREAD

**Issue by iamarpitpatidar** [lostdesign/linked#190] opened 2022-12-02 08:28 UTC
**Describe the bug**
slash(/) does nothing  on type, also it prevents user to hit enter.

**To Reproduce**
1. Install app in ubuntu
2. type /
3. See error

**Expected behavior**
it should show blocks on typing `/` also it should let user to press enter

**Desktop (please complete the following information):**
 - linked version: latest
 - operating system - zorin os 16.2

**Additional context**
wierd, cannot even view about info.

**Comment by lostdesign** [comment] 2022-12-05 10:01
Thanks for your report! Did you ever install linked before it was it your first time?

I am asking this because I feel like that only users that already had linked before the slash menu, face this issue until they switch languages once which resolves the issue.

The about menu once was proposed by someone but then neglected, leaving it back to me. Guess I need to add that then, even if there is nothing important on it.

**Comment by iamarpitpatidar** [comment] 2022-12-05 13:56
no this is the first time..

**Comment by iamarpitpatidar** [comment] 2022-12-07 19:34
well its javascript, I think I can help,.. lemme see what I can do.. 
anything else that you think could help me while debugging this ??

**Comment by lostdesign** [comment] 2022-12-12 08:19
@iamarpitpatidar I suspect that this line is the cause for this
https://github.com/lostdesign/linked/blob/319bccf64eaccbe368c2053063f0b252f809fde1/src/i18n.js#L28

**Comment by vrozkovec** [comment] 2023-02-07 15:19
Hi, I also have this issue. Using latest version 1.5.1 on Linux Mint 20.3, Mate edition.
Had previously linked installed, but did uninstall and complete removal of all assets and it did not help.
Both AppImage and .deb version have the problem.

**Comment by lostdesign** [comment] 2023-02-07 15:37
Thanks for confirming. As mentioned above, switch languages once as a hotfix.

**Comment by vrozkovec** [comment] 2023-02-07 15:42
Thank you, missed that hotfix, menu works now after switching languages.

**Comment by lostdesign** [comment] 2023-06-29 12:51
fixed in https://github.com/lostdesign/linked/releases/tag/v1.5.2

**Closed by lostdesign** 2023-06-29 12:51 UTC
Labels: bug
