### ISSUE TITLE
🐛  - "/" isn't working on macOS 13.

### ISSUE THREAD

**Issue by AedyRawal** [lostdesign/linked#194] opened 2023-06-20 04:01 UTC
"/" key does nothing on macOS 13.

**Comment by lostdesign** [comment] 2023-06-21 07:22
Thanks for your report, it is a duplicate of https://github.com/lostdesign/linked/issues/190

**Closed by lostdesign** 2023-06-21 07:22 UTC
Labels: bug

**Comment by lostdesign** [comment] 2023-06-29 13:02
It has been fixed in https://github.com/lostdesign/linked/releases/tag/v1.5.2
